### ISSUE TITLE
Comparison with Redux-ORM?

### ISSUE THREAD

**Issue by markerikson** [ABASystems/redux-jam#1]
Hi.  Was skimming Github repos and came across this.  Looks kind of interesting.  Any thoughts on how it compares to https://github.com/tommikaikkonen/redux-orm ?

**Comment by furious-luke** [comment]
Hi Mark! Yep, I had a brief look at redux-orm before starting this project. redux-orm looks great, but it didn't look like it would handle synchronisation with a server, which is really what I was after. The main purpose of this project is to provide a way to handle offline operations in a DB like fashion, and then synchronise differences to/from the server via JSON API.
